name: Release
on:
    push:
        branches:
            - master
            - beta
jobs:
    prepare:
        runs-on: ubuntu-latest
        if: "! contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - run: echo "${{ github.event.head_commit.message }}"
    publish:
        needs: prepare
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: npm install
              run: |
                npm install --ignore-scripts
                npm install @semantic-release/changelog @semantic-release/git --ignore-scripts --no-save
            - name: semantic-release
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                npx semantic-release

